Repository sngular/pact-annotation-processor, pull requests merged in 2023-11, with the labels that each got.

#9 README.md update
  README.md
Labels: documentation

#20 Fix for random sizes for collections in complex objects
  pom.xml
  src/main/java/com/sngular/annotation/processor/PactDslProcessor.java
  src/main/java/com/sngular/annotation/processor/model/FieldValidations.java
  src/main/resources/templates/templateDslBuilder.ftlh
Labels: bug, release

#21 Remove deprecated RandomUtils and use RNG instead
  pom.xml
  src/main/java/com/sngular/annotation/processor/mapping/BooleanMapping.java
  src/main/java/com/sngular/annotation/processor/mapping/ByteMapping.java
  src/main/java/com/sngular/annotation/processor/mapping/DecimalMapping.java
  src/main/java/com/sngular/annotation/processor/mapping/IntegerMapping.java
  src/main/java/com/sngular/annotation/processor/mapping/LongMapping.java
  src/main/java/com/sngular/annotation/processor/mapping/ShortMapping.java
  src/main/java/com/sngular/annotation/processor/mapping/StringMapping.java
Labels: enhancement, release

#31 issue-27 - Add support to float
  src/main/java/com/sngular/annotation/processor/PactDslProcessor.java
Labels: bug, release

#32 issue 26 - Correction bug for char
  pom.xml
  src/main/java/com/sngular/annotation/processor/mapping/CharMapping.java
  src/main/resources/templates/templateDslBuilder.ftlh
Labels: bug, release

#40 Adding buildExpectedInstance to dsl builder template
  pom.xml
  src/main/resources/templates/templateDslBuilder.ftlh
Labels: enhancement, release

#30 issue-29 - Add new annotation to ignore generation
  README.md
  checkstyle.xml
  pom.xml
  src/main/java/com/sngular/annotation/pact/DslExclude.java
  src/main/java/com/sngular/annotation/processor/PactDslProcessor.java
  src/main/java/com/sngular/annotation/processor/mapping/ByteMapping.java
  src/main/java/com/sngular/annotation/processor/mapping/DecimalMapping.java
  src/main/java/com/sngular/annotation/processor/mapping/IntegerMapping.java
  src/main/java/com/sngular/annotation/processor/mapping/LongMapping.java
  src/main/java/com/sngular/annotation/processor/mapping/ShortMapping.java
  src/main/java/com/sngular/annotation/processor/mapping/StringMapping.java
  src/main/java/com/sngular/annotation/processor/model/DslComplexField.java
  src/main/java/com/sngular/annotation/processor/model/DslSimpleField.java
  src/main/resources/templates/templateDslBuilder.ftlh
Labels: enhancement, release

#42 README.md update
  README.md
Labels: documentation

#45 issue - 41 - Correction related to BigInteger
  pom.xml
  src/main/java/com/sngular/annotation/processor/PactDslProcessor.java
  src/main/java/com/sngular/annotation/processor/mapping/BigIntegerMapping.java
  src/main/resources/templates/templateDslBuilder.ftlh
Labels: bug, release

#46 issue - 44 - Correction related to generating short
  pom.xml
  src/main/java/com/sngular/annotation/processor/mapping/ShortMapping.java
  src/main/resources/templates/templateDslBuilder.ftlh
Labels: bug, release

#47 Update README.md to adopt correct library name
  README.md
  pom.xml
Labels: documentation, release
